// Controlled vocabulary. Free text is never accepted for role or city.

export const CITIES = [
  "Bangalore", "Mumbai", "Delhi NCR", "Gurgaon", "Noida", "Pune", "Hyderabad",
  "Chennai", "Kolkata", "Ahmedabad", "Jaipur", "Kochi", "Coimbatore",
  "Thiruvananthapuram", "Indore", "Chandigarh", "Bhubaneswar", "Nagpur",
  "Lucknow", "Vadodara", "Surat", "Mysore", "Visakhapatnam", "Mohali", "Remote (India)",
] as const;
export type City = (typeof CITIES)[number];

export const CATEGORIES = [
  "Engineering", "Data & AI", "Design", "Product", "QA", "DevOps & Infra",
  "Security", "IT & Support", "Sales", "Marketing", "Customer Success",
  "Operations", "Finance", "HR", "Legal", "Content", "Consulting", "Management",
] as const;
export type Category = (typeof CATEGORIES)[number];

// role_title -> role_category. ~170 entries.
export const ROLES: Record<string, Category> = {
  "Software Engineer": "Engineering",
  "Senior Software Engineer": "Engineering",
  "Staff Software Engineer": "Engineering",
  "Principal Engineer": "Engineering",
  "Frontend Engineer": "Engineering",
  "Senior Frontend Engineer": "Engineering",
  "Backend Engineer": "Engineering",
  "Senior Backend Engineer": "Engineering",
  "Full Stack Developer": "Engineering",
  "Senior Full Stack Developer": "Engineering",
  "Android Developer": "Engineering",
  "iOS Developer": "Engineering",
  "React Native Developer": "Engineering",
  "Flutter Developer": "Engineering",
  "Java Developer": "Engineering",
  "Python Developer": "Engineering",
  ".NET Developer": "Engineering",
  "PHP Developer": "Engineering",
  "Golang Developer": "Engineering",
  "Node.js Developer": "Engineering",
  "React Developer": "Engineering",
  "Angular Developer": "Engineering",
  "Salesforce Developer": "Engineering",
  "SAP Consultant": "Consulting",
  "Embedded Software Engineer": "Engineering",
  "Firmware Engineer": "Engineering",
  "Game Developer": "Engineering",
  "Blockchain Developer": "Engineering",
  "Technical Lead": "Engineering",
  "Engineering Manager": "Management",
  "Senior Engineering Manager": "Management",
  "Director of Engineering": "Management",
  "VP of Engineering": "Management",
  "CTO": "Management",
  "Solutions Architect": "Engineering",
  "Enterprise Architect": "Engineering",
  "Data Analyst": "Data & AI",
  "Senior Data Analyst": "Data & AI",
  "Business Analyst": "Data & AI",
  "Data Scientist": "Data & AI",
  "Senior Data Scientist": "Data & AI",
  "Machine Learning Engineer": "Data & AI",
  "Senior Machine Learning Engineer": "Data & AI",
  "MLOps Engineer": "Data & AI",
  "AI Engineer": "Data & AI",
  "Data Engineer": "Data & AI",
  "Senior Data Engineer": "Data & AI",
  "Analytics Engineer": "Data & AI",
  "BI Developer": "Data & AI",
  "Research Scientist": "Data & AI",
  "NLP Engineer": "Data & AI",
  "Computer Vision Engineer": "Data & AI",
  "Statistician": "Data & AI",
  "UX Designer": "Design",
  "Senior UX Designer": "Design",
  "UI Designer": "Design",
  "Product Designer": "Design",
  "Senior Product Designer": "Design",
  "UX Researcher": "Design",
  "Visual Designer": "Design",
  "Graphic Designer": "Design",
  "Motion Designer": "Design",
  "Design Lead": "Design",
  "Design Manager": "Design",
  "Illustrator": "Design",
  "Brand Designer": "Design",
  "Product Manager": "Product",
  "Senior Product Manager": "Product",
  "Associate Product Manager": "Product",
  "Group Product Manager": "Product",
  "Director of Product": "Product",
  "Technical Program Manager": "Product",
  "Program Manager": "Product",
  "Project Manager": "Product",
  "Scrum Master": "Product",
  "Product Analyst": "Product",
  "Product Owner": "Product",
  "QA Engineer": "QA",
  "Senior QA Engineer": "QA",
  "SDET": "QA",
  "Automation Test Engineer": "QA",
  "Manual Test Engineer": "QA",
  "Performance Test Engineer": "QA",
  "QA Lead": "QA",
  "DevOps Engineer": "DevOps & Infra",
  "Senior DevOps Engineer": "DevOps & Infra",
  "Site Reliability Engineer": "DevOps & Infra",
  "Platform Engineer": "DevOps & Infra",
  "Cloud Engineer": "DevOps & Infra",
  "Cloud Architect": "DevOps & Infra",
  "Infrastructure Engineer": "DevOps & Infra",
  "Database Administrator": "DevOps & Infra",
  "Network Engineer": "DevOps & Infra",
  "Systems Engineer": "DevOps & Infra",
  "Security Engineer": "Security",
  "Senior Security Engineer": "Security",
  "Security Analyst": "Security",
  "SOC Analyst": "Security",
  "Penetration Tester": "Security",
  "Application Security Engineer": "Security",
  "GRC Analyst": "Security",
  "CISO": "Security",
  "IT Support Engineer": "IT & Support",
  "System Administrator": "IT & Support",
  "Desktop Support Engineer": "IT & Support",
  "IT Manager": "IT & Support",
  "Technical Support Engineer": "IT & Support",
  "Sales Development Representative": "Sales",
  "Business Development Executive": "Sales",
  "Business Development Manager": "Sales",
  "Account Executive": "Sales",
  "Senior Account Executive": "Sales",
  "Key Account Manager": "Sales",
  "Regional Sales Manager": "Sales",
  "Sales Manager": "Sales",
  "Inside Sales Executive": "Sales",
  "Presales Consultant": "Sales",
  "Solutions Engineer": "Sales",
  "VP of Sales": "Sales",
  "Digital Marketing Executive": "Marketing",
  "Digital Marketing Manager": "Marketing",
  "SEO Specialist": "Marketing",
  "Performance Marketing Manager": "Marketing",
  "Growth Marketer": "Marketing",
  "Product Marketing Manager": "Marketing",
  "Brand Manager": "Marketing",
  "Social Media Manager": "Marketing",
  "Marketing Manager": "Marketing",
  "Head of Marketing": "Marketing",
  "Email Marketing Specialist": "Marketing",
  "Customer Success Manager": "Customer Success",
  "Customer Success Associate": "Customer Success",
  "Customer Support Executive": "Customer Success",
  "Technical Account Manager": "Customer Success",
  "Support Team Lead": "Customer Success",
  "Operations Executive": "Operations",
  "Operations Manager": "Operations",
  "Supply Chain Manager": "Operations",
  "Logistics Manager": "Operations",
  "Procurement Manager": "Operations",
  "Business Operations Manager": "Operations",
  "City Operations Manager": "Operations",
  "Warehouse Manager": "Operations",
  "Accountant": "Finance",
  "Senior Accountant": "Finance",
  "Chartered Accountant": "Finance",
  "Financial Analyst": "Finance",
  "Finance Manager": "Finance",
  "Controller": "Finance",
  "Internal Auditor": "Finance",
  "Tax Consultant": "Finance",
  "Treasury Analyst": "Finance",
  "CFO": "Finance",
  "HR Executive": "HR",
  "HR Generalist": "HR",
  "HR Business Partner": "HR",
  "Technical Recruiter": "HR",
  "Talent Acquisition Manager": "HR",
  "HR Manager": "HR",
  "Compensation and Benefits Analyst": "HR",
  "Head of People": "HR",
  "Legal Counsel": "Legal",
  "Senior Legal Counsel": "Legal",
  "Company Secretary": "Legal",
  "Paralegal": "Legal",
  "Compliance Manager": "Legal",
  "Content Writer": "Content",
  "Senior Content Writer": "Content",
  "Technical Writer": "Content",
  "Copywriter": "Content",
  "Content Strategist": "Content",
  "Video Editor": "Content",
  "Editor": "Content",
  "Management Consultant": "Consulting",
  "Senior Consultant": "Consulting",
  "Strategy Manager": "Consulting",
  "Implementation Consultant": "Consulting",
  "Functional Consultant": "Consulting",
  "Chief of Staff": "Management",
  "General Manager": "Management",
  "Country Manager": "Management",
};

export const ROLE_TITLES = Object.keys(ROLES).sort();

/**
 * Employer segment — the field that explains the widest real spread in Indian pay.
 * Engineering at 3-5 years is ~₹7.1 L in IT services and ~₹26.4 L at a product
 * company. Both are true; without this they average into a number describing nobody.
 */
export const SEGMENTS = [
  "IT Services",
  "Product & Internet",
  "GCC",
  "BFSI",
  "Consulting",
  "Startup",
  "Other",
] as const;
export type Segment = (typeof SEGMENTS)[number];

export const SEGMENT_HINTS: Record<Segment, string> = {
  "IT Services": "TCS, Infosys, Wipro, Accenture, Cognizant",
  "Product & Internet": "Flipkart, Zomato, Razorpay, Zoho, Swiggy",
  GCC: "Indian office of a global firm — Amazon, Google, JPMC",
  BFSI: "Banks, insurance, financial services",
  Consulting: "Deloitte, EY, KPMG, McKinsey, ZS",
  Startup: "Under ~500 people, VC-funded",
  Other: "Anything else",
};

export const EMPLOYMENT_TYPES = ["full-time", "contract"] as const;
export const COMPANY_SIZES = ["<50", "50-500", "500-5000", "5000+"] as const;

// Experience buckets, coarse on purpose: granular years make every cell too thin
// to reach n>=8.
export const EXP_BUCKETS = [
  { label: "0-2 yrs", min: 0, max: 2 },
  { label: "3-5 yrs", min: 3, max: 5 },
  { label: "6-9 yrs", min: 6, max: 9 },
  { label: "10-14 yrs", min: 10, max: 14 },
  { label: "15+ yrs", min: 15, max: 60 },
] as const;

export function expBucket(years: number) {
  return EXP_BUCKETS.find((b) => years >= b.min && years <= b.max) ?? EXP_BUCKETS[EXP_BUCKETS.length - 1];
}
